### ISSUE TITLE
Add licencse

### ISSUE THREAD

**Issue by scopatz** [darpa-xdata/xlang#24]
Currently, there isn't one.

**Comment by swadey** [comment]
Assuming that no one objects, I'll add an Apache v2 license.

**Comment by scopatz** [comment]
BSD came in in the the discussion that prompted this, but it is your project :)

**Comment by swadey** [comment]
Either of these would be good.  Just want something liberal and protective...

**Comment by jakirkham** [comment]
+1

**Comment by swadey** [comment]
Sorry about the delay.  I added an MIT licence to this project.

**Comment by aterrel** [comment]
Thanks! @swadey we did discuss this with the team back when it was active and all agreed on MIT.
